const s = {
  entity: "event",
  account_id: "acc_QOsXJiDBQNha83",
  event: "subscription.completed",
  contains: ["subscription", "payment"],
  payload: {
    subscription: {
      entity: {
        id: "sub_QclRCWDe7yWJIE",
        entity: "subscription",
        plan_id: "plan_QTc7P2tnruOuMX",
        customer_id: "cust_QSX2cOk4DyeJj9",
        status: "completed",
        current_start: 1748962703,
        current_end: 1751481000,
        ended_at: 1748962703,
        quantity: 1,
        notes: [],
        charge_at: null,
        start_at: 1748962703,
        end_at: 1748962703,
        auth_attempts: 0,
        total_count: 1,
        paid_count: 1,
        customer_notify: true,
        created_at: 1748962635,
        expire_by: null,
        short_url: null,
        has_scheduled_changes: false,
        change_scheduled_at: null,
        source: "dashboard",
        payment_method: "upi",
        offer_id: null,
        remaining_count: 0,
      },
    },
    payment: {
      entity: {
        id: "pay_QclSNdWUCWVHwk",
        entity: "payment",
        amount: 10000,
        currency: "INR",
        status: "captured",
        order_id: "order_QclRDOot3Chpid",
        invoice_id: "inv_QclRDAGV7zJ1ms",
        international: false,
        method: "upi",
        amount_refunded: 0,
        amount_transferred: 0,
        refund_status: null,
        captured: "1",
        description: "Yearly Subscription (2 months free!)",
        card_id: null,
        bank: null,
        wallet: null,
        vpa: "testuser@razorpay",
        email: "guptas3067@gmail.com",
        contact: "+919920597987",
        customer_id: "cust_QSX2cOk4DyeJj9",
        token_id: "token_QclSOMykfUBMIC",
        notes: { userId: "TDjiZbr2PKcn6A6jtaBVfP6JGgCrOjoy", plan: "PRO" },
        fee: 236,
        tax: 36,
        error_code: null,
        error_description: null,
        acquirer_data: {
          rrn: "001000100002",
          upi_transaction_id: "npci_txn_id_for_QclSNdWUCWVHwk",
        },
        created_at: 1748962703,
      },
    },
  },
  created_at: 1748962711,
};
