FROM node:22-alpine

WORKDIR /app

ARG VITE_BACKEND_URL,VITE_EDITOR_BASE_URL
RUN cat <<EOF > .env 
VITE_BACKEND_URL=$VITE_BACKEND_URL
VITE_EDITOR_BASE_URL=$VITE_EDITOR_BASE_URL
EOF

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/editor ./apps/editor


RUN npm i
RUN npm run db:generate
RUN npm run build:editor

CMD [ "npm", "run", "start:editor" ]