FROM node:22-alpine

WORKDIR /app

RUN apk update && apk add redis


COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend
COPY ./packages ./packages

RUN npm i
RUN npm run db:generate 
RUN npm run build:backend
EXPOSE 3000

CMD sh -c "redis-server & sleep 2 && npm run backend"
