FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/editor ./apps/editor
COPY ./packages ./packages

RUN npm i
RUN npm run db:generate
RUN npm run build:editor
EXPOSE 3000

CMD [ "npm","run","backend" ]