FROM node:22-alpine

WORKDIR /app

ARG VITE_BACKEND_URL
ARG VITE_EDITOR_BASE_URL

RUN echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" >> .env && \
    echo "VITE_EDITOR_BASE_URL=${VITE_EDITOR_BASE_URL}" >> .env

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/editor ./apps/editor


RUN npm i
RUN npm run db:generate
RUN npm run build:editor

CMD [ "npm", "run", "start:editor" ]