FROM node:22-alpine

ARG NEXT_PUBLIC_CREATOR_BASE_URL
WORKDIR /app

COPY ./apps/web ./apps/web
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

RUN echo "NEXT_PUBLIC_CREATOR_BASE_URL=${NEXT_PUBLIC_CREATOR_BASE_URL}" >> ./apps/web/.env 

RUN npm i
RUN npm run build:web
EXPOSE 3000

CMD sh -c " npm run start:web"
