FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN npm i
RUN npm run build:web
EXPOSE 3000

CMD [ "npm","run","backend" ]