FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/creator ./apps/creator
COPY ./packages ./packages

RUN npm i
RUN npm run db:generate
RUN npm run build --filter=creator
EXPOSE 3000

CMD [ "npm","run","backend" ]