FROM node:22-alpine

ARG NEXT_PUBLIC_CREATOR_BASE_URL
WORKDIR /app

COPY ./apps/web ./apps/web
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

RUN echo "NEXT_PUBLIC_CREATOR_BASE_URL=${NEXT_PUBLIC_CREATOR_BASE_URL}" >> ./apps/web/.env && \
    echo "VITE_CREATOR_BASE={VITE_CREATOR_BASE_URL}" >> ./app/web/.env

RUN echo ./apps/web/.env
RUN npm i
RUN npm run build:web
EXPOSE 3000

CMD sh -c "cat ./apps/web/.env && npm run start:web"
