FROM node:22-alpine

WORKDIR /app

ARG VITE_BACKEND_URL,VITE_RAZORPAY_KEY_ID,VITE_CREATOR_BASE_URL
RUN cat <<EOF > .env
VITE_BACKEND_URL=$VITE_BACKEND_URL
VITE_RAZORPAY_KEY_ID=$VITE_RAZORPAY_KEY_ID
VITE_CREATOR_BASE_URL=$VITE_CREATOR_BASE_URL
EOF

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/creator ./apps/creator


RUN npm i
RUN npm run db:generate
RUN npm run build:creator
EXPOSE 3000

CMD [ "npm", "run", "start:creator" ]