name: Build & Deploy Affected Apps

on:
  push:
    branches: [main]
    paths:
      - "apps/backend/**"
      - "packages/database/**"
      - "packages/**"
      - "package.json"
      - "turbo.json"

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.backend_image }}:latest
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            VITE_CREATOR_BASE_URL=${{ secrets.VITE_CREATOR_BASE_URL }}
            VITE_EDITOR_BASE_URL=${{ secrets.VITE_EDITOR_BASE_URL }}
            EDITOR_AUTH_SECRET=${{ secrets.EDITOR_AUTH_SECRET }}
            CREATOR_AUTH_SECRET=${{ secrets.CREATOR_AUTH_SECRET }}
            RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NODEMAILER_USER=${{ secrets.NODEMAILER_USER }}
            NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }}
