name: Build & Deploy Affected Apps

on:
  push:
    branches: [main]
    paths:
      - "apps/editor/**"
      - "packages/**"
      - "package.json"
      - "turbo.json"

jobs:
  deploy:
    name: Deploy Editor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VITE_EDITOR_BASE_URL: ${{ secrets.VITE_EDITOR_BASE_URL }}
            VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          context: .
          file: ./docker/Dockerfile.editor
          push: true
          tags: sahilg99/syncmate-editor:${{ github.sha }}
