name: autofix.ci
on:
  pull_request:
    branches: [main]

jobs:
  build:
  name: Build Repo
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run build

  prettier:
    name: Prettier Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npx prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
