name: Build and Format
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_CREATOR_BASE_URL: ${{ secrets.VITE_CREATOR_BASE_URL }}

  prettier:
    name: Prettier Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npx prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
